name: Create production promotion pull request
on:
  push:
    branches:
      - main
jobs:
  sample:
    runs-on: ubuntu-latest
    steps:
    - name: change
      run: <something file change processing>
    - name: create pr
      uses: peter-evans/create-pull-request@v7
      with:
        branch: "sample"
        title: "auto update"
        body: "auto update dayo!"
        commit-message: "Update!"
        base: main