name: Update Changelog
on:
  push:
    branches:
      - main
jobs:
  updateChangelog:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Update Changelog
        run: |
          git branch -b "sample"
          echo "## Changelog updated on $(date)" >> CHANGELOG.md
          git add .
          git commit -m "Update!"
          git push origin sample
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v7
        with:
          commit-message: update changelog
          title: Update Changelog
          body: Update changelog to reflect release changes
          branch: update-changelog
          base: main